#!/usr/bin/env python3
"""
Generate SOURCES.md with full list of PDFs and news sources.
Called by GitHub Actions after fetching data.
"""

import json
from pathlib import Path

CACHE_DIR = Path(__file__).parent.parent.parent / "cache"
KNOWN_PDFS = Path(__file__).parent.parent.parent / "known_pdfs.json"


def main():
    # Load known PDFs
    with open(KNOWN_PDFS, 'r', encoding='utf-8') as f:
        known = json.load(f)
    
    # Categorize PDFs
    europa = []
    deutschland = []
    
    for url, info in known.get('pdfs', {}).items():
        name = info.get('name', url.split('/')[-1])
        source = info.get('source', '')
        
        entry = {"name": name, "url": url}
        
        if 'volteuropa.org' in url:
            europa.append(entry)
        else:
            deutschland.append(entry)
    
    # Sort by name
    europa.sort(key=lambda x: x['name'])
    deutschland.sort(key=lambda x: x['name'])
    
    # Load news counts
    news_counts = {}
    for nf in CACHE_DIR.glob("news_*.json"):
        with open(nf, 'r', encoding='utf-8') as f:
            articles = json.load(f)
        source_name = nf.stem.replace("news_", "").replace("_", " ").replace("  ", " ")
        news_counts[source_name] = len(articles)
    
    # Generate SOURCES.md
    md = """# 📚 Volt Policies — Full Source List

> Auto-generated by GitHub Actions. Do not edit manually.

---

## 🇪🇺 Volt Europa Policies

### Mapping of Policies (MOP 9.0)

| Challenge | PDF |
|-----------|-----|
"""
    
    # MOP challenges
    mop_files = [e for e in europa if 'MOP' in e['name'] or 'mop' in e['url']]
    for e in europa:
        if 'MOP' in e['name'] or 'challenge' in e['url']:
            name = e['name'].replace('MOP 9 0 - ', 'Challenge — ')
            md += f"| {name} | [PDF]({e['url']}) |\n"
    
    md += """
### Foundational & Other Documents

| Document | PDF |
|----------|-----|
"""
    
    for e in europa:
        if 'MOP' not in e['name'] and 'challenge' not in e['url']:
            md += f"| {e['name']} | [PDF]({e['url']}) |\n"
    
    md += """
---

## 🇩🇪 Volt Deutschland Policies

### Statuten (Statutes)

| Document | PDF |
|----------|-----|
"""
    
    statuten_keywords = ['Satzung', 'Finanzordnung', 'Schiedsgerichtsordnung', 'Wahlordnung', 'Geschäftsordnung']
    for e in deutschland:
        if any(kw in e['name'] for kw in statuten_keywords):
            md += f"| {e['name']} | [PDF]({e['url']}) |\n"
    
    md += """
### Programme

| Document | PDF |
|----------|-----|
"""
    
    for e in deutschland:
        if 'Grundsatzprogramm' in e['name']:
            md += f"| {e['name']} | [PDF]({e['url']}) |\n"
    
    md += """
### Wahlprogramme (Election Programmes)

| Document | PDF |
|----------|-----|
"""
    
    for e in deutschland:
        if 'Wahl' in e['name'] or 'Europawahl' in e['name'] or 'Bundestagswahl' in e['name']:
            md += f"| {e['name']} | [PDF]({e['url']}) |\n"
    
    md += """
### Positionspapiere (Position Papers)

| Document | PDF |
|----------|-----|
"""
    
    position_keywords = ['Position', 'Ehegattensplitting', 'Wehrfähige', 'Nukleare', 'Magnetschwebebahn']
    for e in deutschland:
        if any(kw in e['name'] for kw in position_keywords):
            md += f"| {e['name']} | [PDF]({e['url']}) |\n"
    
    md += """
### Unvereinbarkeitsbeschlüsse (Incompatibility Decisions)

| Document | PDF |
|----------|-----|
"""
    
    for e in deutschland:
        if 'Unvereinbarkeit' in e['name']:
            md += f"| {e['name']} | [PDF]({e['url']}) |\n"
    
    md += f"""
---

## 📰 News Sources

| Source | Articles | Method |
|--------|----------|--------|
"""
    
    total_news = 0
    for source, count in sorted(news_counts.items()):
        method = "Mastodon API" if "Mastodon" in source else "RSS + Scraping"
        md += f"| {source} | {count} | {method} |\n"
        total_news += count
    
    md += f"| **Total** | **{total_news}** | |\n"
    
    md += """
---

*This file is auto-generated. For live counts, see [STATUS.md](STATUS.md).*
"""
    
    # Write SOURCES.md
    sources_path = Path(__file__).parent.parent.parent / "SOURCES.md"
    sources_path.write_text(md, encoding='utf-8')
    print(f"Generated SOURCES.md: {len(europa)} Europa + {len(deutschland)} Deutschland PDFs, {total_news} news articles")


if __name__ == "__main__":
    main()
