#!/usr/bin/env python3
"""
Generate SOURCES.md with full list of PDFs and news sources.
Called by GitHub Actions after fetching data.
"""

import json
from pathlib import Path

CACHE_DIR = Path(__file__).parent.parent.parent / "cache"
KNOWN_PDFS = Path(__file__).parent.parent.parent / "known_pdfs.json"
CHAPTERS_CONFIG = Path(__file__).parent.parent.parent / "scripts" / "chapters.json"


def load_chapters() -> dict:
    if CHAPTERS_CONFIG.exists():
        with open(CHAPTERS_CONFIG, 'r', encoding='utf-8') as f:
            return json.load(f).get("chapters", {})
    return {}


def categorize_pdf(url: str, source: str, chapters: dict) -> str:
    """Determine which country group a PDF belongs to."""
    if 'volteuropa.org' in url:
        return "europa"

    # Check against chapter websites
    for name, info in chapters.items():
        if info.get("website", "").rstrip('/') in url or info.get("website", "").split("//")[-1].split("/")[0] in url:
            return name

    # Fallback to source name
    return source


def main():
    with open(KNOWN_PDFS, 'r', encoding='utf-8') as f:
        known = json.load(f)

    chapters = load_chapters()

    # Categorize PDFs by country
    pdf_by_country: dict[str, list] = {}

    for url, info in known.get('pdfs', {}).items():
        name = info.get('name', url.split('/')[-1])
        source = info.get('source', '')
        country = categorize_pdf(url, source, chapters)
        pdf_by_country.setdefault(country, []).append({"name": name, "url": url})

    # Sort PDFs within each country
    for country in pdf_by_country:
        pdf_by_country[country].sort(key=lambda x: x['name'])

    # Country flags and display names
    COUNTRY_META = {
        "europa": ("🇪🇺", "Volt Europa Policies"),
        "Volt Österreich": ("🇦🇹", "Volt Österreich"),
        "Volt Belgien": ("🇧🇪", "Volt Belgien"),
        "Volt Bulgarien": ("🇧🇬", "Volt Bulgarien"),
        "Volt Kroatien": ("🇭🇷", "Volt Kroatien"),
        "Volt Zypern": ("🇨🇾", "Volt Zypern"),
        "Volt Tschechien": ("🇨🇿", "Volt Tschechien"),
        "Volt Dänemark": ("🇩🇰", "Volt Dänemark"),
        "Volt Deutschland": ("🇩🇪", "Volt Deutschland"),
        "Volt Estland": ("🇪🇪", "Volt Estland"),
        "Volt Finnland": ("🇫🇮", "Volt Finnland"),
        "Volt Frankreich": ("🇫🇷", "Volt Frankreich"),
        "Volt Griechenland": ("🇬🇷", "Volt Griechenland"),
        "Volt Ungarn": ("🇭🇺", "Volt Ungarn"),
        "Volt Irland": ("🇮🇪", "Volt Irland"),
        "Volt Italien": ("🇮🇹", "Volt Italien"),
        "Volt Kosovo": ("🇽🇰", "Volt Kosovo"),
        "Volt Lettland": ("🇱🇻", "Volt Lettland"),
        "Volt Litauen": ("🇱🇹", "Volt Litauen"),
        "Volt Luxemburg": ("🇱🇺", "Volt Luxemburg"),
        "Volt Malta": ("🇲🇹", "Volt Malta"),
        "Volt Niederlande": ("🇳🇱", "Volt Niederlande"),
        "Volt Norwegen": ("🇳🇴", "Volt Norwegen"),
        "Volt Polen": ("🇵🇱", "Volt Polen"),
        "Volt Portugal": ("🇵🇹", "Volt Portugal"),
        "Volt Rumänien": ("🇷🇴", "Volt Rumänien"),
        "Volt Slowakei": ("🇸🇰", "Volt Slowakei"),
        "Volt Slowenien": ("🇸🇮", "Volt Slowenien"),
        "Volt Spanien": ("🇪🇸", "Volt Spanien"),
        "Volt Schweden": ("🇸🇪", "Volt Schweden"),
        "Volt Schweiz": ("🇨🇭", "Volt Schweiz"),
        "Volt Ukraine": ("🇺🇦", "Volt Ukraine"),
        "Volt Vereinigtes Königreich": ("🇬🇧", "Volt Vereinigtes Königreich"),
    }

    # Load news counts
    news_counts = {}
    for nf in sorted(CACHE_DIR.glob("news_*.json")):
        with open(nf, 'r', encoding='utf-8') as f:
            articles = json.load(f)
        source_name = nf.stem.replace("news_", "").replace("_", " ").replace("  ", " ")
        news_counts[source_name] = len(articles)

    # Build MD
    md = """# 📚 Volt Policies — Full Source List

> Auto-generated by GitHub Actions. Do not edit manually.

---

"""

    # PDF sections per country
    if "europa" in pdf_by_country:
        europa_pdfs = pdf_by_country.pop("europa")
        md += """## 🇪🇺 Volt Europa Policies

### Mapping of Policies (MOP 9.0)

| Challenge | PDF |
|-----------|-----|
"""
        for e in europa_pdfs:
            if 'MOP' in e['name'] or 'challenge' in e['url']:
                name = e['name'].replace('MOP 9 0 - ', 'Challenge — ')
                md += f"| {name} | [PDF]({e['url']}) |\n"

        md += """
### Foundational & Other Documents

| Document | PDF |
|----------|-----|
"""
        for e in europa_pdfs:
            if 'MOP' not in e['name'] and 'challenge' not in e['url']:
                md += f"| {e['name']} | [PDF]({e['url']}) |\n"

        md += "\n---\n\n"

    # National chapter PDFs
    for country_name in sorted(pdf_by_country.keys()):
        flag, display = COUNTRY_META.get(country_name, ("🏳️", country_name))
        pdfs = pdf_by_country[country_name]
        md += f"## {flag} {display}\n\n"
        md += "| Document | PDF |\n|----------|-----|\n"
        for p in pdfs:
            md += f"| {p['name']} | [PDF]({p['url']}) |\n"
        md += "\n---\n\n"

    # News sources
    md += """## 📰 News Sources

| Source | Articles | Method |
|--------|----------|--------|
"""
    total_news = 0
    for source, count in sorted(news_counts.items()):
        method = "Mastodon API" if "Mastodon" in source else "Bluesky" if "Bluesky" in source or "bsky" in source else "Instagram" if "Insta" in source else "RSS + Scraping"
        md += f"| {source} | {count} | {method} |\n"
        total_news += count
    md += f"| **Total** | **{total_news}** | |\n"

    md += """
---

*This file is auto-generated. For live counts, see [STATUS.md](STATUS.md).*
"""

    # Write SOURCES.md
    sources_path = Path(__file__).parent.parent.parent / "SOURCES.md"
    sources_path.write_text(md, encoding='utf-8')
    print(f"Generated SOURCES.md: {len(pdf_by_country) + (1 if 'europa' in pdf_by_country else 0)} countries, {total_news} news articles")


if __name__ == "__main__":
    main()
