#!/usr/bin/env python3
"""
Generate STATUS.md with live counts from cache.
Called by GitHub Actions after fetching news + PDFs.
"""

import json
import sys
from pathlib import Path
from datetime import datetime

# Use cache_manager for correct path
sys.path.insert(0, str(Path(__file__).parent))
from cache_manager import get_cache_dir

KNOWN_PDFS = Path(__file__).parent.parent.parent / "known_pdfs.json"


def main():
    CACHE_DIR = get_cache_dir()
    # Count PDFs
    meta_files = list(CACHE_DIR.glob("*_meta.json"))
    pdf_count = len(meta_files)
    
    # Count by source
    europa = 0
    deutschland = 0
    pdf_list = []
    for mf in meta_files:
        with open(mf, 'r', encoding='utf-8') as f:
            meta = json.load(f)
        name = meta.get("document", mf.stem.replace("_meta", ""))
        url = meta.get("url", "")
        pages = len(meta.get("pages", []))
        
        if "volteuropa.org" in url:
            europa += 1
            source = "Europa"
        else:
            deutschland += 1
            source = "Deutschland"
        
        pdf_list.append({
            "name": name,
            "source": source,
            "url": url,
            "pages": pages
        })
    
    # Count news
    news_files = list(CACHE_DIR.glob("news_*.json"))
    news_counts = {}
    total_news = 0
    news_list = []
    
    for nf in news_files:
        with open(nf, 'r', encoding='utf-8') as f:
            articles = json.load(f)
        
        source_name = nf.stem.replace("news_", "").replace("_", " ")
        count = len(articles)
        news_counts[source_name] = count
        total_news += count
        
        for a in articles[:5]:  # Sample
            news_list.append({
                "title": a.get("title", "")[:80],
                "source": source_name,
                "date": a.get("date", "")[:10],
                "link": a.get("link", "")
            })
    
    # Get last update time
    if meta_files:
        last_pdf = max(mf.stat().st_mtime for mf in meta_files)
        last_update = datetime.fromtimestamp(last_pdf).strftime("%Y-%m-%d %H:%M UTC")
    else:
        last_update = "N/A"
    
    # Generate STATUS.md
    status = f"""# 📊 Volt Policies — Live Status

> Auto-generated by GitHub Actions. Last update: **{last_update}**

## Corpus

| Category | Count |
|----------|-------|
| Volt Europa PDFs | {europa} |
| Volt Deutschland PDFs | {deutschland} |
| **Total PDFs** | **{pdf_count}** |
"""
    
    for source, count in sorted(news_counts.items()):
        status += f"| {source} | {count} |\n"
    
    status += f"| **Total News** | **{total_news}** |\n"
    status += f"| **Grand Total** | **{pdf_count + total_news}** |\n"
    
    status += f"""
## Sources

### PDF Sources
- [Volt Europa Policies](https://volteuropa.org/policies/all-policies)
- [Volt Deutschland Statuten](https://voltdeutschland.org/programm/programme/statuten-de)
- [Volt Deutschland Wahlprogramme](https://voltdeutschland.org/programm/programme/wahlprogramme)

### News Sources
- Volt Deutschland News (RSS + Scraping)
- Volt Europa News (RSS + Scraping)
- [Volt in the Press](https://mastodon.social/@voltinthepress) (Mastodon API — all posts)

## CI Workflow

| Workflow | Status | Schedule |
|----------|--------|----------|
| [Update Volt Policies](https://github.com/harrytyp/voltpolicies/actions/workflows/update-news.yml) | ![Update](https://github.com/harrytyp/voltpolicies/actions/workflows/update-news.yml/badge.svg) | Every 6 hours |

---

*This file is auto-generated. Do not edit manually.*
"""
    
    # Write STATUS.md
    status_path = Path(__file__).parent.parent.parent / "STATUS.md"
    status_path.write_text(status, encoding='utf-8')
    print(f"Generated STATUS.md: {pdf_count} PDFs, {total_news} news articles")


if __name__ == "__main__":
    main()
