#!/usr/bin/env python3
"""
Generate STATUS.md with live counts from cache.
Called by GitHub Actions after fetching news + PDFs.
"""

import json
import sys
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).parent))
from cache_manager import get_cache_dir

KNOWN_PDFS = Path(__file__).parent.parent.parent / "known_pdfs.json"
CHAPTERS_CONFIG = Path(__file__).parent.parent.parent / "scripts" / "chapters.json"


def load_chapters() -> dict:
    if CHAPTERS_CONFIG.exists():
        with open(CHAPTERS_CONFIG, 'r', encoding='utf-8') as f:
            return json.load(f).get("chapters", {})
    return {}


def get_country_flag(name: str) -> str:
    flags = {
        "Volt Europa": "🇪🇺",
        "Volt Albanien": "🇦🇱", "Volt Österreich": "🇦🇹",
        "Volt Belgien": "🇧🇪", "Volt Bulgarien": "🇧🇬",
        "Volt Kroatien": "🇭🇷", "Volt Zypern": "🇨🇾",
        "Volt Tschechien": "🇨🇿", "Volt Dänemark": "🇩🇰",
        "Volt Estland": "🇪🇪", "Volt Finnland": "🇫🇮",
        "Volt Frankreich": "🇫🇷", "Volt Deutschland": "🇩🇪",
        "Volt Griechenland": "🇬🇷", "Volt Ungarn": "🇭🇺",
        "Volt Irland": "🇮🇪", "Volt Italien": "🇮🇹",
        "Volt Kosovo": "🇽🇰", "Volt Lettland": "🇱🇻",
        "Volt Litauen": "🇱🇹", "Volt Luxemburg": "🇱🇺",
        "Volt Malta": "🇲🇹", "Volt Niederlande": "🇳🇱",
        "Volt Norwegen": "🇳🇴", "Volt Polen": "🇵🇱",
        "Volt Portugal": "🇵🇹", "Volt Rumänien": "🇷🇴",
        "Volt Slowakei": "🇸🇰", "Volt Slowenien": "🇸🇮",
        "Volt Spanien": "🇪🇸", "Volt Schweden": "🇸🇪",
        "Volt Schweiz": "🇨🇭", "Volt Ukraine": "🇺🇦",
        "Volt Vereinigtes Königreich": "🇬🇧",
    }
    return flags.get(name, "🏳️")


def main():
    CACHE_DIR = get_cache_dir()
    chapters = load_chapters()

    # Count PDFs by source
    meta_files = list(CACHE_DIR.glob("*_meta.json"))
    pdf_count = len(meta_files)

    pdf_by_source = {}
    europa_pdfs = 0
    for mf in meta_files:
        with open(mf, 'r', encoding='utf-8') as f:
            meta = json.load(f)
        url = meta.get("url", "")
        if "volteuropa.org" in url:
            source = "Volt Europa"
            europa_pdfs += 1
        else:
            # Try to identify country from URL
            source = "Other"
            for name, info in chapters.items():
                domain = info.get("website", "").split("//")[-1].split("/")[0]
                if domain and domain in url:
                    source = name
                    break
            if source == "Other":
                source = "Volt Deutschland"
        pdf_by_source[source] = pdf_by_source.get(source, 0) + 1

    # Count news
    news_files = list(CACHE_DIR.glob("news_*.json"))
    news_counts = {}
    total_news = 0

    for nf in news_files:
        with open(nf, 'r', encoding='utf-8') as f:
            articles = json.load(f)
        source_name = nf.stem.replace("news_", "").replace("_", " ")
        count = len(articles)
        news_counts[source_name] = count
        total_news += count

    # Get last update time
    if meta_files:
        last_pdf = max(mf.stat().st_mtime for mf in meta_files)
        last_update = datetime.fromtimestamp(last_pdf).strftime("%Y-%m-%d %H:%M UTC")
    else:
        last_update = "N/A"

    # Generate STATUS.md
    status = f"""# 📊 Volt Policies — Live Status

> Auto-generated by GitHub Actions. Last update: **{last_update}**

## Corpus

| Category | Count |
|----------|-------|
"""

    for source, count in sorted(pdf_by_source.items()):
        flag = get_country_flag(source)
        status += f"| {flag} {source} PDFs | {count} |\n"
    status += f"| **Total PDFs** | **{pdf_count}** |\n"

    for source, count in sorted(news_counts.items()):
        status += f"| {source} | {count} |\n"
    status += f"| **Total News** | **{total_news}** |\n"
    status += f"| **Grand Total** | **{pdf_count + total_news}** |\n"

    # Sources section
    status += """
## Sources

### PDF Sources
- [Volt Europa Policies](https://volteuropa.org/policies/all-policies)
"""
    for name in sorted(chapters.keys()):
        info = chapters[name]
        flag = get_country_flag(name)
        status += f"- [{flag} {name}]({info['website']})\n"

    status += """
### News Sources
"""
    for source in sorted(news_counts.keys()):
        method = "Mastodon API" if "Mastodon" in source else "Bluesky" if "Bluesky" in source or "bsky" in source else "Instagram" if "Insta" in source else "RSS"
        chapter_key = source.replace(" News", "")
        if chapter_key in chapters:
            flag = get_country_flag(chapter_key)
            status += f"- {flag} {source} ({method})\n"
        else:
            status += f"- {source} ({method})\n"

    status += """
## CI Workflow

| Workflow | Status | Schedule |
|----------|--------|----------|
| [Update Volt Policies](https://github.com/harrytyp/voltpolicies/actions/workflows/update-news.yml) | ![Update](https://github.com/harrytyp/voltpolicies/actions/workflows/update-news.yml/badge.svg) | Daily at 06:00 UTC |

---

*This file is auto-generated. Do not edit manually.*
"""

    # Write STATUS.md
    status_path = Path(__file__).parent.parent.parent / "STATUS.md"
    status_path.write_text(status, encoding='utf-8')
    print(f"Generated STATUS.md: {pdf_count} PDFs from {len(pdf_by_source)} countries, {total_news} news articles")


if __name__ == "__main__":
    main()
